Spielen/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/<str:username>/', views.profile_detail, name='profile_detail'),
    path('signup/', views.signup, name='signup'),
    path('profile_update/<str:username>/', views.profile_update, name="profile_update"),
    path('follow/<int:pk>/', views.follow, name='follow'),
    path('cardnews/', views.cardnews, name='cardnews'),
    path('cardnews_2/', views.cardnews_2, name="cardnews_2"),
]

search/urls.py
from django.urls import path
from . import views

app_name = 'search'

urlpatterns = [
    path('result/', views.result, name='result'),
    path('', views.search, name='search'),
    path('detail/<str:playid>/', views.detail, name='detail'),
    path('review/<int:pk>/', views.review, name='review'),
    path('review/<str:playid>/', views.review, name='review'),
    path('review_create/<str:playid>/', views.review_create, name="review_create"),
    path('review_detail/<int:pk>/', views.review_detail, name='review_detail'),

    path('play_create/<str:username>/', views.play_create, name='play_create'),

    path('<str:playid>/like', views.to_my_heart, name='to_my_heart'),

    path('recommend/', views.recommend, name='recommend'),
    path('review/update/<int:pk>/', views.review_update, name='review_update')
]

theatre/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('search/', include('search.urls', namespace='search')),
    path('summer_note/', include('django_summernote.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.conf import settings
from multiselectfield import MultiSelectField

from search.models import Theater
# Create your models here.

gerne_name = (
        (1, '비극 '),
        (2, '희극 '),
        (3, '비희극 '),
        (4, '소극 '),
        (5, '통속극 '),
        (6, '공포 '),
        (7, '스릴러 '),
        (8, '추리극 '),
        (9, '로맨틱 '),
        )

character = (
        (1, '예술적'),
        (2, '실험적'),
        (3, '대중적'),
        (4, 'NTLIVE/해외생중계공연'),
        (5, '감동적'),
        (6, '웃음만발'),
        (7, '아이와 함께'),
        (8, '어머! 눈감아'),
        (9, '원작 기반'),
        )


class Profile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        )
    upload_path = 'profile/%Y/%m/%d'
    image = models.ImageField(
        upload_to='profile/%Y/%m/%d',
        blank=True,
        null=True,
        )
    birth_date = models.DateField(
        null=True,
        blank=True)

    liebe_t = models.CharField(
        blank=True,
        null=True,
        verbose_name='당신의 가장 좋아하는 연극 하나만!! 알려주세욯ㅎ??',
        max_length=30,
        )
    liebe_a = models.CharField(
        blank=True,
        null=True,
        verbose_name='좋아하는 배우는요? 딱 한사람만 말하셔야 되용ㅎㅎ 프로그램을 그따구로 해서 ㅋㅋㅋ',
        max_length=100
        )

    recommand_t = models.TextField(
        blank=True,
        null=True,
        verbose_name='짧은 자기 소개!',
        )
    price = models.IntegerField(
        blank=True,
        null=True,
        verbose_name='선호가격'
        )

    def image_url(self):
        if self.image:
            image_url = self.image.url
        else:
            image_url = '/static/img/default_profile_image.jpg'
        return image_url

    group_image = models.ImageField(
        upload_to='profile/%Y/%m/%d',
        blank=True,
        null=True,
        verbose_name='극단사진 giveme',
        )

    is_groupuser = models.BooleanField(
        default=False
        )

    follow = models.ManyToManyField(
        "self",
        related_name='follower',
        blank=True,
        symmetrical=False
        )

    genre_select = MultiSelectField(
        max_length=250,
        blank=True,
        null=True,
        choices=gerne_name,
        verbose_name='극의 장르 '
    )

    play_char = MultiSelectField(
            max_length=250,
            blank=True,
            null=True,
            choices=character,
            verbose_name='극의 특징',
            )

    address_lat = models.FloatField(
        null=True,
        blank=True,
        verbose_name='위도'
        )

    address_lng = models.FloatField(
        null=True,
        blank=True,
        verbose_name='경도'
        )



    def __str__(self):
        return '{0}'.format(self.user.username)

    def group_image_url(self):
        if self.group_image:
            group_image_url = self.group_image.url
        else:
            group_image_url = '/static/img/default_profile_image.jpg'
        return group_image_url

search/models.py
from django.db import models
from django.conf import settings
from multiselectfield import MultiSelectField


# Create your models here.
gerne_name = (
        (1, '비극 '),
        (2, '희극 '),
        (3, '비희극 '),
        (4, '소극 '),
        (5, '통속극 '),
        (6, '공포 '),
        (7, '스릴러 '),
        (8, '추리극 '),
        (9, '로맨틱 '),
        )

character = (
        (1, '예술적'),
        (2, '실험적'),
        (3, '대중적'),
        (4, 'NTLIVE/해외생중계공연'),
        (5, '감동적'),
        (6, '웃음만발'),
        (7, '아이와 함께'),
        (8, '어머! 눈감아'),
        (9, '원작 기반'),
        )


class Play(models.Model):
    to_my_heart = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        related_name='play_to_my_heart',
        )

    playid = models.CharField(
        max_length=15,
        verbose_name='연극ID')
    placeid = models.CharField(
        null=True,
        max_length=15,
        verbose_name='공연장소ID')
    name = models.CharField(
        max_length=20,
        verbose_name='제목')
    start_date = models.DateField(
        verbose_name='시작일')
    end_date = models.DateField(
        verbose_name='종료일')
    place = models.CharField(
        max_length=20,
        verbose_name='장소')
    actor = models.CharField(
        max_length=60,
        verbose_name='배우')
    staff = models.CharField(
        null=True,
        max_length=60,
        verbose_name='제작')
    runtime = models.CharField(
        max_length=10,
        verbose_name='런타임')
    poster = models.URLField(
        null=True,
        blank=True,
        verbose_name='포스터이미지경로')
    styurl1 = models.CharField(
        max_length=100,
        null=True,
        blank=True,
        verbose_name='소개이미지1')
    styurl2 = models.CharField(
        max_length=100,
        null=True,
        blank=True,
        verbose_name='소개이미지2')
    styurl3 = models.CharField(
        max_length=100,
        null=True,
        blank=True,
        verbose_name='소개이미지3')
    styurl4 = models.CharField(
        max_length=100,
        null=True,
        blank=True,
        verbose_name='소개이미지4')
    price = models.CharField(
        max_length=10,
        verbose_name='가격')
    time = models.CharField(
        max_length=80,
        verbose_name='공연시간')
    minprice = models.IntegerField(
        default=1,
        verbose_name='최소가격')

    grade = models.IntegerField(
        default=0,
        null=True,
        verbose_name='순위',
        )

    rate = models.DecimalField(
        max_digits=10,
        decimal_places=1,
        default=0,
        verbose_name='평점'
        )

    genre_select = MultiSelectField(
        max_length=250,
        blank=True,
        null=True,
        choices=gerne_name,
        verbose_name='극의 장르 '
        )

    Text_base = models.BooleanField(
        default=False,
        verbose_name='희곡 기반',
        )

    play_char = MultiSelectField(
        max_length=250,
        blank=True,
        null=True,
        choices=character,
        verbose_name='극의 특징',
        )

    theater = models.ForeignKey(
        'Theater',
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        verbose_name='극장'
        )

    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.CASCADE
        )

    poster_self = models.ImageField(
        upload_to='poster/%Y/%m/%d',
        blank=True,
        null=True,
        verbose_name='포스터이미지')
    styurl1_self = models.ImageField(
        upload_to='styurl1/%Y/%m/%d',
        null=True,
        blank=True,
        verbose_name='이미지1')
    styurl2_self = models.ImageField(
        upload_to='styurl2/%Y/%m/%d',
        null=True,
        blank=True,
        verbose_name='이미지2')
    styurl3_self = models.ImageField(
        upload_to='styurl3/%Y/%m/%d',
        null=True,
        blank=True,
        verbose_name='이미지3')
    styurl4_self = models.ImageField(
        upload_to='styurl4/%Y/%m/%d',
        null=True,
        blank=True,
        verbose_name='이미지4')

    confirmed = models.BooleanField(
        default=False,
        verbose_name='검증')

    user_upload = models.BooleanField(
        default=False,
        verbose_name='유저입력')

    lat = models.FloatField(
        null=True,
        blank=True,
        verbose_name='위도'
        )

    lng = models.FloatField(
        null=True,
        blank=True,
        verbose_name='경도'
        )


    def __str__(self):
        return '{0}'.format(self.name)


class Tag(models.Model):
    name = models.CharField(max_length=15)

    def __str__(self):
        return self.name


class Review(models.Model):
    play = models.ForeignKey(
        Play,
        on_delete=models.CASCADE
        )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='author'
        )
    title = models.CharField(
        max_length=30,
        verbose_name='제목')
    content = models.TextField()

    rate = models.IntegerField(
        default=0,
        verbose_name='평점'
        )

    tag = models.ManyToManyField(
        Tag,
        blank=True,
        related_name='tag_comment',
        )

    img1 = models.ImageField(
        upload_to='reviewimg/{0}/'.format(play.name),
        null=True,
        blank=True,
        verbose_name='이미지1'
        )
    img2 = models.ImageField(
        upload_to='reviewimg/{0}/'.format(play.name),
        null=True,
        blank=True,
        verbose_name='이미지2'
        )
    img3 = models.ImageField(
        upload_to='reviewimg/{0}/'.format(play.name),
        null=True,
        blank=True,
        verbose_name='이미지3'
        )
    img4 = models.ImageField(
        upload_to='reviewimg/{0}/'.format(play.name),
        null=True,
        blank=True,
        verbose_name='이미지4'
        )

class Theater(models.Model):
    placeid = models.CharField(
        max_length=15,
        verbose_name='공연장ID')
    name = models.CharField(
        max_length=30,
        verbose_name='공연장이름')
    theater_count = models.IntegerField(
        null=True,
        blank=True,
        verbose_name='공연장수')
    tel = models.CharField(
        max_length=20,
        null=True,
        blank=True,
        verbose_name='전화번호')
    page = models.URLField(
        null=True,
        blank=True)
    address = models.CharField(
        max_length=50,
        null=True,
        blank=True,
        verbose_name='주소')
    latitude = models.FloatField(
        null=True,
        blank=True)
    longitude = models.FloatField(
        null=True,
        blank=True)

    def __str__(self):
        return '{0}'.format(self.name)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import (
    authenticate,
    login as auth_login,
    logout as auth_logout,
    )
from django.contrib.auth.decorators import login_required
from django.http import (
    HttpResponse,
    JsonResponse
    )
from .forms import (
    AuthForm,
    SignupForm,
    SignupProfileForm,
    GroupProfileForm
    )

from django.urls import reverse
from django.conf import settings
from .models import Profile
from search.models import (
    Play,
    Review,
    Theater
    )

# Create your views here.


def login(request):
    form = AuthForm(request, request.POST or None)
    if request.method == "POST" and form.is_valid():

        auth_login(request, form.get_user())
        next = request.GET.get('next') or settings.LOGIN_REDIRECT_URL

        return redirect(next)

    ctx = {
        'form': form
    }
    return render(request, 'accounts/login.html', ctx)


def logout(request):
    auth_logout(request)
    return redirect(reverse('accounts:login'))

## 여기서 내가 좋아요 한  파일을 가져올 수 있어야 함
## 유저를 가져와야 하는구나

def profile_detail(request, username):
    profile = Profile.objects.all()
    my_profile = profile.get(user__username=username)
    follower = my_profile.follow.all()

    review = []
    review_play = []
    for i in follower:
        for j in list(Review.objects.filter(author_id=i.user.pk)):
            if j.play.playid not in review_play:
                review.append(j)
                review_play.append(j.play.playid)

    play = Play.objects.all()
    play_to_my_heart = play.filter(to_my_heart__username=username)

    review_user = Review.objects.filter(author_id=my_profile.user.pk)


    tag_user = set()
    for a in review_user:
        tag_user |= set(a.tag.all())

    # review_follower = review.filter(author_id=follower.user_id)
    print(play_to_my_heart.all())
    print(review)
    ctx = {
        'review_profile':review_user,
        'review_user':tag_user,
        'play_to_my_heart':play_to_my_heart.all(),
        'profile':my_profile,
        'follower_review':review,
        'play':play,
        }
    # play_to_select = play_to_my_heart.get('name')

    return render(request, 'accounts/profile.html', ctx)


def login_and_redirect_next(request, user):
    auth_login(request, user)
    next_url = request.GET.get('next') or settings.LOGIN_REDIRECT_URL
    return redirect(next_url)


def signup(request):
    signup_form = SignupForm(request.POST or None)
    profile_form = SignupProfileForm(request.POST or None, request.FILES or None)

    if request.method == 'GET':
        if request.is_ajax():
            if request.GET['theater'] == 'true':
                profile_form = GroupProfileForm()
            return render(request, 'accounts/form.html', {
                'signup_form': signup_form,
                'profile_form': profile_form,
                })
    else:
        if request.is_ajax():
            pk = int(request.POST.get('theater'))
            theater = Theater.objects.get(pk=pk)
            return JsonResponse({'lat': theater.latitude,
                'lng': theater.longitude})
        elif signup_form.is_valid():
            if request.POST.get('is_groupuser'):
                print(request.POST.get('is_groupuser'))
                profile_form = GroupProfileForm(request.POST, request.FILES or None)
            if profile_form.is_valid():
                user = signup_form.save()
                profile = profile_form.save(commit=False)
                profile.user = user
                profile.save()
                return login_and_redirect_next(request, user)
    ctx = {
        'signup_form': signup_form,
        'profile_form': profile_form,
    }
    return render(request, 'accounts/signup.html', ctx)

## 개인 유저는 왜?? 가입시에 사진  첨부가 안되는지??
## 개인 유저는 프로필 수정시에 왜??

@login_required
def profile_update(request, username):
    if request.user.profile.is_groupuser:
        form = GroupProfileForm(request.POST or None, request.FILES or None, instance=request.user.profile)
    else:
        form = SignupProfileForm(request.POST or None, request.FILES or None, instance=request.user.profile)
    if request.method == "POST" and form.is_valid():
        form.save()
        return redirect(reverse('accounts:profile_detail', kwargs={
            'username': username,
            }))

    ctx = {
        'form': form,
        'profile': Profile.objects.get(user=request.user)
    }
    return render(request, 'accounts/profile_create.html', ctx)


@login_required
def follow(request, pk):
    if request.method == "POST":
        follow = Profile.objects.get(user__pk=pk)
        print(follow)
        if request.user.profile.follow.filter(user__pk=pk).exists():
            request.user.profile.follow.remove(follow)
        else:
            request.user.profile.follow.add(follow)
        ctx = {
            'did_follow': request.user.profile.follow.filter(user__pk=pk).exists(),
        }

        return render(request, 'accounts/follow_button.html', ctx)
    else:
        return HttpResponse(status=404)


@login_required
def cardnews(request):
    if request.method == "POST":
        print(request.POST)
        profile = Profile.objects.filter(user=request.user)
        genre = request.POST.getlist('genre[]')
        character = request.POST.getlist('character[]')
        profile.update(genre_select=genre, play_char=character)
        print(genre)
        print(character)

    return render(request, 'accounts/cardnews.html')

@login_required
def cardnews_2(request):
    if request.method == "POST":
        actor = request.POST.get('actor')
        staff = request.POST.get('staff')
        price = int(request.POST.get('price'))
        profile = Profile.objects.filter(user=request.user)
        profile.update(liebe_t=staff, liebe_a=actor, price=price)
        return redirect(reverse('search:recommend'))
    return render(request, 'accounts/cardnews2.html')

accounts/templates/accounts/follow_button.html
<button class="btn {% if did_follow %}followed{% endif %} ">
팔로우
</button>

accounts/templates/accounts/form.html
{% csrf_token %}
      {{ signup_form.as_p }}
      {{ profile_form.as_p }}

accounts/templates/accounts/profile_create.html
{% extends 'base.html' %}

{% block accounts %}

<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}


</form>
<div class="add">
      <label for="map">위치</label>
      <input class="controls" name="map" type="text" id="pac-input" value=""></input>

      <div id="map"></div>
      </div>
      <br>
<button type="submit" class="btn" id="sub">프로필 수정</button>
<script type="text/javascript">
    $('#id_address_lat').css('display', 'none');
    $('#id_address_lat').prevAll().css('display', 'none');
    $('#id_address_lng').css('display', 'none');
    $('#id_address_lng').prevAll().css('display', 'none');
      $('#id_birth_date').addClass('datepicker');
    $('.datepicker').pickadate({
        selectMonths: true, // Creates a dropdown to control month
        selectYears: 15, // Creates a dropdown of 15 years to control year,
        today: 'Today',
        clear: 'Clear',
        close: 'Ok',
        closeOnSelect: false, // Close upon selecting a date,
        format: 'yyyy-mm-dd'
      });
    $('#sub').click(function(){
          $('form').submit();
        });
      $('#id_is_groupuser').prevAll().css('display', 'none');
</script>
<script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAeZY_e4UJ_3tJa_TPqgHdjB-DztK2TYtw&callback=initMap&libraries=places">
    </script>
<script language="javascript">
var map;
var markers = [];
var geocoder;

function initMap() {
        // var uluru = {lat: parseFloat("37.2345"), lng: parseFloat("125.3453")};
        map = new google.maps.Map(document.getElementById('map'), {
          zoom: 15,
          center: new google.maps.LatLng(parseFloat("{{ profile.address_lat }}"), parseFloat("{{ profile.address_lng }}"))
        });
        geocoder = new google.maps.Geocoder();
        var marker = new google.maps.Marker({
          position: map.center,
          map: map,
          draggable:true,
          title:"Drag me!"
        });
        var defaultBounds = new google.maps.LatLngBounds(
        new google.maps.LatLng(33.8902, 125.1759),
        new google.maps.LatLng(38.8474, 132.2631));

        var input = document.getElementById('pac-input');

        var searchBox = new google.maps.places.SearchBox(input, {
            bounds: defaultBounds });
        // geocodeAddress(geocoder, map);




        // Listen for the event fired when the user selects a prediction and retrieve
      // more details for that place.
      searchBox.addListener('places_changed', function() {
        initMap();
        marker.setMap(null)
        $('#id_theater').val(null);
        var places = searchBox.getPlaces();

        if (places.length == 0) {
          return;
        }
        $("#id_address_lat").val(places[0].geometry.location.lat());
          $("#id_address_lng").val(places[0].geometry.location.lng());
        // Clear out the old markers.
        markers.forEach(function(marker) {
          marker.setMap(null);
        });
        markers = [];

        // For each place, get the icon, name and location.
        var bounds = new google.maps.LatLngBounds();
        places.forEach(function(place) {
          if(place != places[0]){ return; }
          if (!place.geometry) {
            console.log("Returned place contains no geometry");
            return;
          }
          var icon = {
            url: place.icon,
            size: new google.maps.Size(71, 71),
            origin: new google.maps.Point(0, 0),
            anchor: new google.maps.Point(17, 34),
            scaledSize: new google.maps.Size(25, 25)
          };

          // Create a marker for each place.
          markers.push(new google.maps.Marker({
            map: map,
            // icon: icon,
            draggable: true,
            title: place.name,
            position: place.geometry.location
          }));
                  markers[0].addListener('drag', function(){
          $("#id_address_lat").val(markers[0].position.lat());
          $("#id_address_lng").val(markers[0].position.lng());
          $('#pac-input').val('');
        });

          if (place.geometry.viewport) {
            // Only geocodes have viewport.
            bounds.union(place.geometry.viewport);
          } else {
            bounds.extend(place.geometry.location);
          }
        });
        map.fitBounds(bounds);
      });
            }
      function geocodeAddress(geocoder, resultsMap) {
        var address = document.getElementById('pac-input').value;
        geocoder.geocode({'address': address}, function(results, status) {
          if (status === 'OK') {
            resultsMap.setCenter(results[0].geometry.location);
            // var marker = new google.maps.Marker({
            //   map: resultsMap,
            //   position: results[0].geometry.location
            // });
            console.log(results[0].geometry);
          } else {
            alert('Geocode was not successful for the following reason: ' + status);
          }
        });
      }

</script>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block accounts %}

<div class="login_start">
  {% if request.user.is_authenticated %}
  <h3> 이미 로그인을 하셨어요!! 로그아웃 하고 싶어요??</h3>
  <form method="POST">
  <button type="submit" action="{% url 'accounts:logout' %}">
    로그아웃
  </button>
  </form>
  {% else %}
    <p style="text-align:center;"> SIGN UP </p>
    <p style="text-align:center;">
    <button class="normal btn" style="border-radius:10px;">
      일반회원
    </button>
    <button class="theater btn" style="border-radius:10px;">
      극단회원
    </button>
    </p>
    <br>
    <form method="POST" id="signup" enctype="multipart/form-data">
      {% csrf_token %}
      {{ signup_form.as_p }}
      {{ profile_form.as_p }}
    </form>
    {% include 'accounts/map.html' %}
    <button class="btn center-align" id="sub" type="submit" >회원가입하기</button>


    <script type="text/javascript">
$('#id_birth_date').addClass('datepicker');
    $('.datepicker').pickadate({
        selectMonths: true, // Creates a dropdown to control month
        selectYears: 15, // Creates a dropdown of 15 years to control year,
        today: 'Today',
        clear: 'Clear',
        close: 'Ok',
        closeOnSelect: false, // Close upon selecting a date,
        format: 'yyyy-mm-dd'
      });
    var theater = false;
        $('#id_address_lat').css('display', 'none');
        $('#id_address_lat').prevAll().css('display', 'none');
        $('#id_address_lng').css('display', 'none');
        $('#id_address_lng').prevAll().css('display', 'none');
    $('#sub').click(function(){
      $('#signup').submit();
    });
    $('#id_is_groupuser').prevAll().css('display', 'none');
      $('.normal').click(function(e) {
        var url = "{% url 'accounts:signup' %}";
        $.get(url,
          { theater: false })
        .done(function(r) {
          $('#signup').html(r);
          $('#id_is_groupuser').prevAll().css('display', 'none');
    $('#id_address_lat').css('display', 'none');
    $('#id_address_lat').prevAll().css('display', 'none');
    $('#id_address_lng').css('display', 'none');
    $('#id_address_lng').prevAll().css('display', 'none');
        });
      });
      $('.theater').click(function(e) {
        var url = "{% url 'accounts:signup' %}";
        var theatre = { theater: true };
        $.get(url, theatre)
        .done(function(r) {
          $('#signup').html(r);
          $('#id_is_groupuser').attr('checked', 'true').prevAll().css('display', 'none');
    $('#id_address_lat').css('display', 'none');
    $('#id_address_lat').prevAll().css('display', 'none');
    $('#id_address_lng').css('display', 'none');
    $('#id_address_lng').prevAll().css('display', 'none');
        });
      });
    </script>

<script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAeZY_e4UJ_3tJa_TPqgHdjB-DztK2TYtw&callback=initMap&libraries=places">
    </script>
<script language="javascript">
var map;
var markers = [];
var geocoder;

function initMap() {
        // var uluru = {lat: parseFloat("37.2345"), lng: parseFloat("125.3453")};
        map = new google.maps.Map(document.getElementById('map'), {
          zoom: 15,
          center: new google.maps.LatLng(34.397, 127.644)
        });
        geocoder = new google.maps.Geocoder();
        // var marker = new google.maps.Marker({
        //   position: map.center,
        //   map: map,
        //   draggable:true,
        //   title:"Drag me!"
        // });
        var defaultBounds = new google.maps.LatLngBounds(
        new google.maps.LatLng(33.8902, 125.1759),
        new google.maps.LatLng(38.8474, 132.2631));

        var input = document.getElementById('pac-input');

        var searchBox = new google.maps.places.SearchBox(input, {
            bounds: defaultBounds });
        geocodeAddress(geocoder, map);




        // Listen for the event fired when the user selects a prediction and retrieve
      // more details for that place.
      searchBox.addListener('places_changed', function() {
        initMap();
        $('#id_theater').val(null);
        var places = searchBox.getPlaces();

        if (places.length == 0) {
          return;
        }
        $("#id_address_lat").val(places[0].geometry.location.lat());
          $("#id_address_lng").val(places[0].geometry.location.lng());
        // Clear out the old markers.
        markers.forEach(function(marker) {
          marker.setMap(null);
        });
        markers = [];

        // For each place, get the icon, name and location.
        var bounds = new google.maps.LatLngBounds();
        places.forEach(function(place) {
          if(place != places[0]){ return; }
          if (!place.geometry) {
            console.log("Returned place contains no geometry");
            return;
          }
          var icon = {
            url: place.icon,
            size: new google.maps.Size(71, 71),
            origin: new google.maps.Point(0, 0),
            anchor: new google.maps.Point(17, 34),
            scaledSize: new google.maps.Size(25, 25)
          };

          // Create a marker for each place.
          markers.push(new google.maps.Marker({
            map: map,
            // icon: icon,
            draggable: true,
            title: place.name,
            position: place.geometry.location
          }));
                  markers[0].addListener('drag', function(){
          $("#id_address_lat").val(markers[0].position.lat());
          $("#id_address_lng").val(markers[0].position.lng());
          $('#pac-input').val('');
        });

          if (place.geometry.viewport) {
            // Only geocodes have viewport.
            bounds.union(place.geometry.viewport);
          } else {
            bounds.extend(place.geometry.location);
          }
        });
        map.fitBounds(bounds);
      });
            }
      function geocodeAddress(geocoder, resultsMap) {
        var address = document.getElementById('pac-input').value;
        geocoder.geocode({'address': address}, function(results, status) {
          if (status === 'OK') {
            resultsMap.setCenter(results[0].geometry.location);
            // var marker = new google.maps.Marker({
            //   map: resultsMap,
            //   position: results[0].geometry.location
            // });
            console.log(results[0].geometry);
          } else {
            alert('Geocode was not successful for the following reason: ' + status);
          }
        });
      }

</script>

  {% endif %}
</div>
{% endblock %}