Spielen/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/<str:username>/', views.profile_detail, name='profile_detail'),
    path('signup/', views.signup, name='signup'),
    path('profile_update/<str:username>/', views.profile_update, name="profile_update"),
    path('follow/<int:pk>/', views.follow, name='follow'),
    path('cardnews/', views.cardnews, name='cardnews'),
    path('cardnews_2/', views.cardnews_2, name="cardnews_2"),
]

search/urls.py
from django.urls import path
from . import views

app_name = 'search'

urlpatterns = [
    path('result/', views.result, name='result'),
    path('', views.search, name='search'),
    path('detail/<str:playid>/', views.detail, name='detail'),
    path('review/<int:pk>/', views.review, name='review'),
    path('review/<str:playid>/', views.review, name='review'),
    path('review_create/<str:playid>/', views.review_create, name="review_create"),
    path('review_detail/<int:pk>/', views.review_detail, name='review_detail'),

    path('play_create/<str:username>/', views.play_create, name='play_create'),

    path('<str:playid>/like', views.to_my_heart, name='to_my_heart'),

    path('recommend/', views.recommend, name='recommend'),
    path('review/update/<int:pk>/', views.review_update, name='review_update')
]

theatre/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('search/', include('search.urls', namespace='search')),
    path('summer_note/', include('django_summernote.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models


class Play(models.Model):
    playid = models.CharField(
        max_length=15,
        verbose_name='연극ID')
    placeid = models.CharField(
        null=True,
        max_length=15,
        verbose_name='공연장소ID')
    name = models.CharField(
        max_length=20,
        verbose_name='이름')
    start_date = models.DateField(
        blank=True,
        null = True,
        verbose_name='시작일')
    end_date = models.DateField(
        blank=True,
        null = True,
        verbose_name='종료일')
    place = models.CharField(
        max_length=20,
        verbose_name='장소')
    actor = models.CharField(
        max_length=60,
        verbose_name='배우')
    staff = models.CharField(
        null=True,
        max_length=60,
        verbose_name='제작')
    runtime = models.CharField(
        max_length=10,
        verbose_name='런타임')
    poster = models.URLField(
        verbose_name='포스터이미지경로')
    styurl1 = models.CharField(
        max_length=100,
        verbose_name='소개이미지1')
    styurl2 = models.CharField(
        max_length=100,
        null = True,
        blank= True,
        verbose_name='소개이미지2')
    styurl3 = models.CharField(
        max_length=100,
        null=True,
        blank=True,
        verbose_name='소개이미지3')
    styurl4 = models.CharField(
        max_length=100,
        null=True,
        blank= True,
        verbose_name='소개이미지4')
    price = models.CharField(
        max_length=10,
        verbose_name='가격')
    time = models.CharField(
        max_length=80,
        verbose_name='공연시간')
    minprice = models.IntegerField(
        default=1,
        verbose_name='최소가격')

    grade = models.IntegerField(
        default=0,
        null=True,
        verbose_name='순위',
        )
    genre = models.CharField(
        null = True,
        blank= True,
        max_length=50,
        verbose_name='장르'
        )

    Text_base = models.BooleanField(
        default = False,
        verbose_name='희곡 기반',
        )

    play_char = models.CharField(
        max_length= 30,
        verbose_name ='극의 특징',
        blank =True,
        null = True,
        )


    def __str__(self):
        return '{0}'.format(self.name)

search/models.py
from django.db import models
from django.conf import settings
from multiselectfield import MultiSelectField


# Create your models here.
gerne_name = (
        (1, '비극 '),
        (2, '희극 '),
        (3, '비희극 '),
        (4, '소극 '),
        (5, '통속극 '),
        (6, '공포 '),
        (7, '스릴러 '),
        (8, '추리극 '),
        (9, '로맨틱 '),
        )

character = (
        (1, '예술적'),
        (2, '실험적'),
        (3, '대중적'),
        (4, 'NTLIVE/해외생중계공연'),
        (5, '감동적'),
        (6, '웃음만발'),
        (7, '아이와 함께'),
        (8, '어머! 눈감아'),
        (9, '원작 기반'),
        )


class Play(models.Model):
    to_my_heart = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        related_name='play_to_my_heart',
        )

    playid = models.CharField(
        max_length=15,
        verbose_name='연극ID')
    placeid = models.CharField(
        null=True,
        max_length=15,
        verbose_name='공연장소ID')
    name = models.CharField(
        max_length=20,
        verbose_name='제목')
    start_date = models.DateField(
        verbose_name='시작일')
    end_date = models.DateField(
        verbose_name='종료일')
    place = models.CharField(
        max_length=20,
        verbose_name='장소')
    actor = models.CharField(
        max_length=60,
        verbose_name='배우')
    staff = models.CharField(
        null=True,
        max_length=60,
        verbose_name='제작')
    runtime = models.CharField(
        max_length=10,
        verbose_name='런타임')
    poster = models.URLField(
        null=True,
        blank=True,
        verbose_name='포스터이미지경로')
    styurl1 = models.CharField(
        max_length=100,
        null=True,
        blank=True,
        verbose_name='소개이미지1')
    styurl2 = models.CharField(
        max_length=100,
        null=True,
        blank=True,
        verbose_name='소개이미지2')
    styurl3 = models.CharField(
        max_length=100,
        null=True,
        blank=True,
        verbose_name='소개이미지3')
    styurl4 = models.CharField(
        max_length=100,
        null=True,
        blank=True,
        verbose_name='소개이미지4')
    price = models.CharField(
        max_length=10,
        verbose_name='가격')
    time = models.CharField(
        max_length=80,
        verbose_name='공연시간')
    minprice = models.IntegerField(
        default=1,
        verbose_name='최소가격')

    grade = models.IntegerField(
        default=0,
        null=True,
        verbose_name='순위',
        )

    rate = models.DecimalField(
        max_digits=10,
        decimal_places=1,
        default=0,
        verbose_name='평점'
        )

    genre_select = MultiSelectField(
        max_length=250,
        blank=True,
        null=True,
        choices=gerne_name,
        verbose_name='극의 장르 '
        )

    Text_base = models.BooleanField(
        default=False,
        verbose_name='희곡 기반',
        )

    play_char = MultiSelectField(
        max_length=250,
        blank=True,
        null=True,
        choices=character,
        verbose_name='극의 특징',
        )

    theater = models.ForeignKey(
        'Theater',
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        verbose_name='극장'
        )

    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.CASCADE
        )

    poster_self = models.ImageField(
        upload_to='poster/%Y/%m/%d',
        blank=True,
        null=True,
        verbose_name='포스터이미지')
    styurl1_self = models.ImageField(
        upload_to='styurl1/%Y/%m/%d',
        null=True,
        blank=True,
        verbose_name='이미지1')
    styurl2_self = models.ImageField(
        upload_to='styurl2/%Y/%m/%d',
        null=True,
        blank=True,
        verbose_name='이미지2')
    styurl3_self = models.ImageField(
        upload_to='styurl3/%Y/%m/%d',
        null=True,
        blank=True,
        verbose_name='이미지3')
    styurl4_self = models.ImageField(
        upload_to='styurl4/%Y/%m/%d',
        null=True,
        blank=True,
        verbose_name='이미지4')

    confirmed = models.BooleanField(
        default=False,
        verbose_name='검증')

    user_upload = models.BooleanField(
        default=False,
        verbose_name='유저입력')

    lat = models.FloatField(
        null=True,
        blank=True,
        verbose_name='위도'
        )

    lng = models.FloatField(
        null=True,
        blank=True,
        verbose_name='경도'
        )


    def __str__(self):
        return '{0}'.format(self.name)


class Tag(models.Model):
    name = models.CharField(max_length=15)

    def __str__(self):
        return self.name


class Review(models.Model):
    play = models.ForeignKey(
        Play,
        on_delete=models.CASCADE
        )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='author'
        )
    title = models.CharField(
        max_length=30,
        verbose_name='제목')
    content = models.TextField()

    rate = models.IntegerField(
        default=0,
        verbose_name='평점'
        )

    tag = models.ManyToManyField(
        Tag,
        blank=True,
        related_name='tag_comment',
        )

    img1 = models.ImageField(
        upload_to='reviewimg/{0}/'.format(play.name),
        null=True,
        blank=True,
        verbose_name='이미지1'
        )
    img2 = models.ImageField(
        upload_to='reviewimg/{0}/'.format(play.name),
        null=True,
        blank=True,
        verbose_name='이미지2'
        )
    img3 = models.ImageField(
        upload_to='reviewimg/{0}/'.format(play.name),
        null=True,
        blank=True,
        verbose_name='이미지3'
        )
    img4 = models.ImageField(
        upload_to='reviewimg/{0}/'.format(play.name),
        null=True,
        blank=True,
        verbose_name='이미지4'
        )

class Theater(models.Model):
    placeid = models.CharField(
        max_length=15,
        verbose_name='공연장ID')
    name = models.CharField(
        max_length=30,
        verbose_name='공연장이름')
    theater_count = models.IntegerField(
        null=True,
        blank=True,
        verbose_name='공연장수')
    tel = models.CharField(
        max_length=20,
        null=True,
        blank=True,
        verbose_name='전화번호')
    page = models.URLField(
        null=True,
        blank=True)
    address = models.CharField(
        max_length=50,
        null=True,
        blank=True,
        verbose_name='주소')
    latitude = models.FloatField(
        null=True,
        blank=True)
    longitude = models.FloatField(
        null=True,
        blank=True)

    def __str__(self):
        return '{0}'.format(self.name)

search/forms.py
from .models import (
    Play,
    Review,
    )
from django import forms

import sys

from django.core import validators
from django.utils.translation import ugettext_lazy as _


class MaxValueMultiFieldValidator(validators.MaxLengthValidator):
    code = 'max_multifield_value'

    def clean(self, x):
        return len(','.join(x))


class MinChoicesValidator(validators.MinLengthValidator):
    message = _(u'You must select a minimum of  %(limit_value)d choices.')
    code = 'min_choices'


class MaxChoicesValidator(validators.MaxLengthValidator):
    message = _(u'You must select a maximum of  %(limit_value)d choices.')
    code = 'max_choices'


if sys.version_info[0] == 2:
    string = basestring  # noqa: F821
    string_type = unicode  # noqa: F821
else:
    string = str
    string_type = string


def get_max_length(choices, max_length, default=200):
    if max_length is None:
        if choices:
            return len(','.join([string_type(key) for key, label in choices]))
        else:
            return default
    return max_length


class MultiSelectFormField(forms.MultipleChoiceField):
    widget = forms.CheckboxSelectMultiple

    def __init__(self, *args, **kwargs):
        self.min_choices = kwargs.pop('min_choices', None)
        self.max_choices = kwargs.pop('max_choices', None)
        self.max_length = kwargs.pop('max_length', None)
        super(MultiSelectFormField, self).__init__(*args, **kwargs)
        self.max_length = get_max_length(self.choices, self.max_length)
        self.validators.append(MaxValueMultiFieldValidator(self.max_length))
        if self.max_choices is not None:
            self.validators.append(MaxChoicesValidator(self.max_choices))
        if self.min_choices is not None:
            self.validators.append(MinChoicesValidator(self.min_choices))


class CreatePlayForm(forms.ModelForm):
    class Meta:
        model = Play
        exclude = ['playid', 'placeid', 'minprice', 'grade', 'rate', 'genre_select', 'play_char', 'poster', 'styurl1', 'styurl2', 'styurl3', 'styurl4', 'to_my_heart', 'confirmed', 'user_upload', 'author']
        widgets = {
            'start_date' : forms.DateInput(attrs={'class':'vDateField'}),
            'end_date' : forms.DateInput()
        }


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['title', 'content', 'rate', 'tag', 'img1', 'img2', 'img3', 'img4']
        widgets = {
            'rate': forms.HiddenInput(),
            }

search/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block search %}

<div class="row" style="width: 1000px; background: #DBDBDB; margin: 0 auto;">
<div class ="poster_img" style="text-align:left;">
  <img src="{{ play.poster }}" style="width: 250px; height: 300px; display: inline-block;">
</div>
<div class="play_infor" style="text-align:left">
 <div class="row" style="margin-bottom: 0px">
      <h1 id="play_name">{{ play.name }}</h1>
        <span class="flow-text">
            <div class="star_box">
                <i class="material-icons first star {{ play.name }}">star_border</i>
                <i class="material-icons star {{ play.name }}">star_border</i>
                <i class="material-icons star {{ play.name }}">star_border</i>
                <i class="material-icons star {{ play.name }}">star_border</i>
                <i class="material-icons star {{ play.name }}">star_border</i>
                <span>{{ play.rate }}</span>
          </div>
            <h3 style="font-size:30px">{{ play.start_date }} ~ {{ play.end_date }}</h3>
            <h3 style="font-size:20px"> 출연진:  {{ play.actor }}</h3>
            <h3 style="font-size:20px"> 스탭진:  {{ play.staff }}</h3>
            <h3 style="font-size:20px"> 가격:  {{ play.price }}</h3>
       </span>
    </div>
  </div>

  <script type="text/javascript">
    var rate = "{{ play.rate }}";
    var star = document.getElementsByClassName("star {{ play.name }}");
    for(var i=0; i<parseInt(rate); i++) {
      star[i].innerHTML = "star";
    }
    if((rate%1) >= 0.5){
      star[i].innerHTML = "star_half";
    }
  </script>
  <div class="heart_button">
  <p style="margin-bottom: 40px; margin-top: 0px;">
    <a id= "to_my_heart_button" style="text-align:center;"href="{% url 'search:to_my_heart' play.playid %}" >

      {% include 'to_my_heart_button.html'%}
    </a>
  </p>
</div>
    </div>
    <script>
        $('#to_my_heart_button').click(function(e) {
            var self = $(this);
            var url = $(this).attr('href');

            $.post(url)
                .done(function(r) {
                    self.html(r);
                })
                .fail(function() {
                    alert('오류가 발생했습니다 ')
                });
                return false;
            });

          </script>

          </div>
  <div class="row" style="width: 1000px; background: #EDEDED;">
    <div class="col s12">
      <ul class="tabs">
        <li class="tab col s6 l6"><a href="#test1">상세정보</a></li>
        <li class="tab col s6 l6"><a class="active" href="#test2">리뷰보기 </a></li>

      </ul>
    </div>

    <div id="test1" class="col s12" style="text-align:center">
  {% if play.user_upload %}

  {% if play.styurl1_self|length > 4 %}
  <img src="{{ play.styurl1_self.url }}">
  {% else %}
  <p> i'm sorry but 상세정보가 없습니다 </p>

  {% endif %}
  {% if play.styurl2_self|length > 4 %}
  <img src="{{ play.styurl2_self.url }}">
  {% endif %}
  <br>
  {% if play.styurl3_self|length > 4 %}
  <img src="{{ play.styurl3_self.url }}">
  {% endif %}
  <br>
  {% if play.styurl4_self|length > 4 %}
  <img src="{{ play.styurl4_self.url }}">
  {% endif %}

  {% else %}

  {% if play.styurl1|length > 4 %}
  <img src="{{ play.styurl1 }}">
  {% else %}
  <p> i'm sorry but 상세정보가 없습니다. 하지만 때론 운에 맡겨보는것도!! 좋아요  </p>

  {% endif %}
  <br>
  {% if play.styurl2|length > 4 %}
  <img src="{{ play.styurl2 }}">
  {% endif %}
  <br>
  {% if play.styurl3|length > 4 %}
  <img src="{{ play.styurl3 }}">
  {% endif %}
  <br>
  {% if play.styurl4|length > 4 %}
  <img src="{{ play.styurl4 }}">
  {% endif %}

  {% endif %}

  <div id="map"></div>
<br>
<script language="javascript">
function initMap() {
        var uluru = {lat: parseFloat("{% if play.theater %} {{ play.theater.latitude }} {% else %} {{ play.lat }} {% endif %}"), lng: parseFloat("{% if play.theater %} {{ play.theater.longitude }} {% else %} {{ play.lng }} {% endif %}")};
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 15,
          center: uluru
        });
        var marker = new google.maps.Marker({
          position: uluru,
          map: map
        });
        console.log(uluru.lat);
      }


function winOpen1()
{
        window.open("{% url 'search:review' play.playid %}", "newWin", "width=1000px, height=1000px, toolbar=no, scroll=no");
}
function winOpen2()
{
        window.open("{% url 'search:review_create' play.playid %}", "newWin", "width=1000px, height=1000px, toolbar=no, scroll=no");
}
</script>
<script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAeZY_e4UJ_3tJa_TPqgHdjB-DztK2TYtw&callback=initMap">
    </script>
    </div>

    <div id="test2" class="col s12" style=" width: 80%; margin: auto 100px; text-align: center;">
      {% if review.count %}

    <div class="review_create_button" style="text-align: center; display: inline-block; margin: 15px auto;">
      <a href="{% url 'search:review_create' play.playid %}" class="btn">리뷰 작성하기</a>
    </div>

  {% for a in review %}

  <div class="review_show">
    <div class="card horizontal" style="position:relative; background: white;">
 <!--     <div class="card-image">
        <img src="https://lorempixel.com/100/190/nature/6">
      </div>  -->
      <div class="card-stacked">
        <div class="card-content">
          <span><a href="{% url 'accounts:profile_detail' a.author.username %}">{{ a.author.username }}</a></span>
          <!--별점 추가하기 줄바꿈이 아니니까 p 태그 또는 br 태그 사용금지 -->
          <span class="star_box">
                <i class="material-icons first star {{ a.title }}">star_border</i>
                <i class="material-icons star {{ a.title }}">star_border</i>
                <i class="material-icons star {{ a.title }}">star_border</i>
                <i class="material-icons star {{ a.title }}">star_border</i>
                <i class="material-icons star {{ a.title }}">star_border</i>
                <span><h5 style="display: inline-block;">{{ a.rate }}</h5></span>
            <script type="text/javascript">
              var rate = parseInt("{{ a.rate }}");
              var star = document.getElementsByClassName("star {{ a.title }}");
              for(var i=0; i<rate; i++) {
                star[i].innerHTML = "star";
              }
            </script>
          </span>
          <a href="{% url 'search:review_detail' a.pk %}"><p>{{ a.content }}</p></a>
          <!--
            <p>a.review의 또 tag여기가 그 태그가 들어갈 부분 -->
        {% for i in a.tag.all %}
              <div class="chip" style="font-color:black">
                {{ i.name }}
              </div>
              {% empty %}
              <p>붙은 태그가 없습니다.</p>
              {% endfor %}
        </div>
        <div class="card-action">
          <div>
            {% if a.img1 %}
            <a href="#modal1" class="modal-trigger" alt="{% url 'search:review_detail' a.pk %}">
            <img src="{{ a.img1.url }}" class="review_img" alt="1">
            </a>
            {% endif %}
            {% if a.img2 %}
            <a href="#modal1" class="modal-trigger" alt="{% url 'search:review_detail' a.pk %}">
            <img src="{{ a.img2.url }}" class="
            review_img" alt="2">
            </a>
            {% endif %}
            {% if a.img3 %}
            <a href="#modal1" class="modal-trigger" alt="{% url 'search:review_detail' a.pk %}">
            <img src="{{ a.img3.url }}" class="review_img" alt="3">
            </a>
            {% endif %}
            {% if a.img4 %}
            <a href="#modal1" class="modal-trigger" alt="{% url 'search:review_detail' a.pk %}">
            <img src="{{ a.img4.url }}" class="review_img" alt="4">
            </a>
    {% endif %}
          </div>
   {% if request.user == a.author %}
      <a href="{% url 'search:review_update' a.pk %}" class="btn" style="float:right;">리뷰 수정하기</a>
      {% endif %}

        </div>
      </div>
    </div>
  </div>

{% endfor %}

<div id="modal1" class="modal">
    <div class="modal-content">

    </div>
    <div class="modal-footer">
      <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat">닫기</a>
    </div>
  </div>
    <script type="text/javascript">
      $('.modal-trigger').click(function() {
        var url = $(this).attr('alt');
        var img = $(this).children('img').attr('src');
        console.log(img);
        $.post(url, {img:img}).done(function(r){
          $('.modal .modal-content').html(r);
          $('.modal .reviewimg').find('img').attr('src', img);
        });
        console.log(url);
        // $.post()
      });
    </script>
{% else %}
<p>작성된 리뷰가 없습니다.</p>
 <div>
    <a href="{% url 'search:review_create' play.playid %}" class="btn">리뷰 작성하기</a>
    </div>
{% endif %}
{% endblock %}

search/templates/recommend.html
{% extends 'base.html' %}

{% block search %}

<div class="recommend">
  <h1>취향저격</h1>
  {% if request.user.is_authenticated %}
    {% for i in recommend %}
    <a href="{% url 'search:detail' i.playid %}">
      <img src="{{ i.poster }}" style="display: inline-block; width: 250px; height: 300px;"></a>

    {% endfor %}
  {% endif %}
</div>
<div class="actor">
  <h1>당신이 좋아하는 사람 출연</h1>
    {% for i in recommend_actor %}
      <a href="{% url 'search:detail' i.playid %}">
      <img src="{{ i.poster }}" style="display: inline-block; width: 250px; height: 300px;"></a>

      {% empty %}
      <strong>추천할 연극이 없습니다ㅠ</strong>
    {% endfor %}
</div>
<div class="staff">
  <h1>당신이 좋아하는 사람 제작</h1>
    {% for i in recommend_staff %}
    <a href="{% url 'search:detail' i.playid %}">
      <img src="{{ i.poster }}" style="display: inline-block; width: 250px; height: 300px;"></a>

      {% empty %}
      <strong>추천할 연극이 없습니다ㅠ</strong>
    {% endfor %}
</div>
<div class="price">
  <h1>당신의 주머니사정을 고려한 추천</h1>
    {% for i in recommend_price %}
    <a href="{% url 'search:detail' i.playid %}">
      <img src="{{ i.poster }}" style="display: inline-block; width: 250px; height: 300px;"></a>

    {% endfor %}
</div>


<a href="{% url 'accounts:cardnews' %}" class="btn">추천 다시받기</a>
{% endblock %}

search/templates/result.html
{% extends 'base.html' %}

{% block search %}
<div class="row" style="margin-left: 12%;">
{% for a in result %}

  <div class="col s12 m7 l10">
    <div class="card horizontal">
      <div class="card-image">
        <img src="{{ a.poster }}" class="poster">
      </div>
      <div class="card-stacked">
        <div class="card-content">
          <p><h4 style="margin-top: 0;">{{ a.name }}</h4></p>
          <p>{{ a.actor }}</p>
          <p>{{ a.staff }}</p>
          <p>{{ a.start_date }}</p>
          <p>{{ a.end_date }}</p>
          <p>{{ a.price }}</p>
        </div>
        <div class="card-action">
          <a href="{% url 'search:detail' a.playid %}">자세히 보기</a>
        </div>
      </div>
    </div>
  </div>

{% endfor %}
</div>
{% endblock %}

search/templates/review.html
{% extends 'base.html' %}

{% block search %}
{% if review.count %}
{% for a in review %}
  <div class="col s12 m7">

    <div class="card horizontal">
 <!--     <div class="card-image">
        <img src="https://lorempixel.com/100/190/nature/6">
      </div>  -->
      <div class="card-stacked">

        <div class="card-content">
          <a href="{% url 'search:review_detail' a.pk %}"><p><strong>{{ a.title|safe }}<strong></p></a>
          <p><a href="{% url 'accounts:profile_detail' a.author.username %}">{{ a.author.username }}</a></p>
        </div>
        <div class="card-action">
          <div class="star_box">
                <i class="material-icons first star {{ a.title }}">star_border</i>
                <i class="material-icons star {{ a.title }}">star_border</i>
                <i class="material-icons star {{ a.title }}">star_border</i>
                <i class="material-icons star {{ a.title }}">star_border</i>
                <i class="material-icons star {{ a.title }}">star_border</i>
                <span><h5 style="display: inline-block;">{{ a.rate }}</h5></span>
            <script type="text/javascript">
              var rate = parseInt("{{ a.rate }}");
              var star = document.getElementsByClassName("star {{ a.title }}");
              for(var i=0; i<rate; i++) {
                star[i].innerHTML = "star";
              }
            </script>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endfor %}
{% else %}
<p>작성된 리뷰가 없습니다.</p>

{% endif %}
{% if review.count %}
<a href="{% url 'search:review_create' review.first.play.playid %}" class="btn">리뷰 작성하기</a>
{% endif %}
{% endblock %}

search/templates/review_create.html
{% extends 'base.html' %}

{% block search %}
<div class="create" style="text-align:center;">
<form method="POST" id="review_form" enctype="multipart/form-data">
{% csrf_token %}
{{ form.as_p }}
  <br>
  <div class="star_box">
    <i class="material-icons first star">star_border</i>
    <i class="material-icons star">star_border</i>
    <i class="material-icons star">star_border</i>
    <i class="material-icons star">star_border</i>
    <i class="material-icons star">star_border</i>
  </div>
  <span class="rate" style="color: white; text-align:center;"></span>
  <br>
<button type="submit">리뷰 작성하기</button>

<script type="text/javascript">

  // $('#review_form').submit(function(e) {
  //   e.preventDefault();
  //   var title = $('#id_title').val();
  //   var content = $('#id_content').val();
  //   var tag = $('#id_tag').val();
  //   var img1 = $('#id_img1').val();
  //   var img2 = $('#id_img2').val();
  //   var img3 = $('#id_img3').val();
  //   var img4 = $('#id_img4').val();


  //   $.post('{% url "search:review_create" play.playid %}', {
  //     title: title,
  //     content: content,
  //     img1: img1,
  //     img2: img2,
  //     img3: img3,
  //     img4: img4,
  //     tag: tag,
  //     rate: parseInt($('.rate').html())
  //   }).done(function(){
  //   console.log('ok');
  //   // location.href = '{% url "search:review" play.playid %}';
  // });
  // });

  $('textarea').addClass('materialize-textarea');
  $('input:file').addClass('input-field');
  $('.star').mouseover(function(){
    var star = $('.first');
    $(this).html('star');
    $(this).prevAll().html('star');

    console.log($(this).prevAll().length+1);
  });

  $('.star').mouseout(function(){
    $('.star').html('star_border');
  });

  $('.star').click(function(){
    var star = $('.first');
    if($(this).hasClass('star')){
      $(this).html('star');
      $(this).prevAll().html('star');
      $(this).nextAll().html('star_border');
      var rate = $(this).prevAll().length+1;
      $('#id_rate').val(rate);
      $(this).removeClass('star');
      $(this).prevAll().removeClass('star');
    }else {
      $(this).html('star');
      $(this).prevAll().html('star');
      $(this).nextAll().html('star_border');
      var rate = $(this).prevAll().length+1;
      $('#id_rate').val(rate);
      $(this).nextAll().addClass('star');
    }
  });
</script>
</form>
</div>
{% endblock %}

search/templates/review_diary.html
{% extends 'base.html' %}

{% block search %}

{% endblock %}