Spielen/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/<str:username>/', views.profile_detail, name='profile_detail'),
    path('signup/', views.signup, name='signup'),
    path('profile_update/<str:username>/', views.profile_update, name="profile_update"),
    path('follow/<int:pk>/', views.follow, name='follow'),
    path('cardnews/', views.cardnews, name='cardnews'),
    path('cardnews_2/', views.cardnews_2, name="cardnews_2"),
]

search/urls.py
from django.urls import path
from . import views

app_name = 'search'

urlpatterns = [
    path('result/', views.result, name='result'),
    path('', views.search, name='search'),
    path('detail/<str:playid>/', views.detail, name='detail'),
    path('review/<int:pk>/', views.review, name='review'),
    path('review/<str:playid>/', views.review, name='review'),
    path('review_create/<str:playid>/', views.review_create, name="review_create"),
    path('review_detail/<int:pk>/', views.review_detail, name='review_detail'),

    path('play_create/<str:username>/', views.play_create, name='play_create'),

    path('<str:playid>/like', views.to_my_heart, name='to_my_heart'),

    path('recommend/', views.recommend, name='recommend'),
    path('review/update/<int:pk>/', views.review_update, name='review_update')
]

theatre/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('search/', include('search.urls', namespace='search')),
    path('summer_note/', include('django_summernote.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

theatre/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>야!극장고?</title>
  <script
  src="http://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>
  <!-- Compiled and minified CSS -->

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{% static 'css/theatre.css' %}">
  <script type="text/javascript" src="{% static 'js/ajax_settings.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/event.js' %}"></script>

  {% block js %}{% endblock %}

  <style type="text/css">
   body {
      background-image: url("{% static 'img/body.png' %}");
      background-repeat: no-repeat;
      background-attachment: fixed;
      background-position: top;
      background-size: cover;
      background-color: gray;
    }
</style>
</head>

<body>
  <div class="navbar-fixed">
  <nav>
    <div class="nav-wrapper">
      <a href="{% url 'search:search' %}" class="brand-logo" style="margin-left: 160px;">야!극장고?<i class="material-icons">star</i></a>
      {% if request.user.is_authenticated %}
        {% if request.user.profile.is_groupuser %}
        <a href="{% url 'search:play_create' request.user.username %}" class="btn">공연 올리기</a>
        {% else %}
        {% if request.user.profile.genre_select or request.user.profile.play_char %}
        <a href="{% url 'search:recommend' %}" class="btn">추천서비스</a>
        {% else %}
      <a href="{% url 'accounts:cardnews' %}" class="btn">추천서비스</a>
        {% endif %}
      {% endif %}
      {% endif %}
      <ul id="nav-mobile" class="right hide-on-med-and-down" style="margin-right: 160px;">
        {% if request.user.is_authenticated %}
        <li><a href="{% url 'accounts:profile_detail' request.user.username %}">{{ request.user }}</a></li>
        <li><a href="{% url 'accounts:login' %}">Log Out</a></li>
        {% else %}
        <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
        <li>
          <a href="{% url 'accounts:login' %}">Log In</a>
        </li>
      {% endif %}
      </ul>
    </div>
  </nav>
  </div>
<main>
{% block search %}{% endblock %}
{% block accounts %}{% endblock %}
</main>

</body>
</html>